33/apim backend sps
lucashuet93/apiops-vnet-github pull request #48
Opened 2023-08-25 15:04 UTC by aaheiev

- Add SP's with APIM contributor permissions 
- Save SP's as Kubernetes secrets

2023-08-28 15:42 UTC, lucashuet93 requested changes
The additions of the AKS related infrastructure are awesome, but I don't want to lose the functionality the repository currently provides. The infrastructure it currently deploys is closely tied to the /apimartifacts contents. For instance, the Application Insights Instrumentation Key is stored as a Key Vault secret via Terraform. The /apimartifacts folder has a named value that point to the Instrumentation Key secret. 

I'd like to add the AKS functionality on top of what currently exists, if possible. It looks like if I deployed the infra, then ran the publisher against said infra as outlined by the README, it would not work properly.

2023-08-28 15:42 UTC, lucashuet93 commented on infrastructure/services.tf
> +resource "azurerm_key_vault" "akv" {
Does the application insights instrumentation key get stored as a Key Vault secret?

2023-08-29 09:05 UTC, ross-p-smith commented on infrastructure/datasources.tf
> +data "azurerm_role_definition" "aks_cluster_admin" {
Can we put a comment on what these magic strings equate to for future developers?

2023-08-29 09:38 UTC, ross-p-smith commented
I've checkout this PR and when I run `make infra` I get the following error: 

```
vscode ➜ /workspaces/apiops-vnet-github (33/apim-backend-sps) $ make infra
infra

Initializing the backend...
Initializing modules...
╷
│ Error: Error inspecting states in the "local" backend:
│     Error retrieving keys for Storage Account "apimmvetfstate": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'infra' could not be found."
│ 
│ Prior to changing backends, Terraform inspects the source and destination
│ states to determine what kind of migration steps need to be taken, if any.
│ Terraform failed to load the states. The data in both the source and the
│ destination remain unmodified. Please resolve the above error and try again.
```

2023-08-29 16:55 UTC, closed without merging