Use envsubst from apim_templates to apim_artifacts
lucashuet93/apiops-vnet-github pull request #54
Opened 2023-08-29 18:48 UTC by ross-p-smith

Fixes #22

Two new commands `make artifacts-dev` and `make artifacts-prod` that will take the files in apim_templates and create an apim_artifacts folder. These will have all of the correct names / resource ids based on the .ENV file that was created by `make infra`.

TODO: It would be nice to solve the server.urls tags in the specification.yml so that you didn't have to specify the server name

2023-08-29 19:08 UTC, lucashuet93 requested changes
Looks great! Could you add some content to the README so it's clear to the user what is happening? 

For instance, even though we just discussed this, I was looking wondering "How is <WILL BE REPLACED BY CREATING ARTIFACTS> going to be replaced by envsubst?" but then realized it isnt, it's overwritten by configuration.ENV.yaml which more clearly relies on envsubst. Not sure that all needs to be explained but some reference to the artifacts would be great.

2023-08-29 19:10 UTC, lucashuet93 submitted a review, later dismissed

2023-08-30 12:45 UTC, aaheiev approved these changes

2023-08-30 12:58 UTC, lucashuet93 approved these changes

2023-08-30 13:03 UTC, merged